# Generated by Django 3.1.3 on 2020-11-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood_donor',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='blood_donor',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
