# Generated by Django 3.1.3 on 2020-12-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blood_recipient',
            name='gender',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
    ]
