# Generated by Django 3.1.3 on 2020-11-18 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20201118_1854'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='name',
            new_name='City',
        ),
    ]
