# Generated by Django 3.1.3 on 2020-11-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20201118_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='event',
            name='details',
            field=models.TextField(default='', max_length=150),
        ),
    ]
